# To run Dev
# mvn spring-boot:run
# java -jar ./target/aws-0.0.1-SNAPSHOT.jar --spring-profiles.active=dev

# To run production
# mvn package
# java -jar ./target/aws-0.0.1-SNAPSHOT.jar --spring-profiles.active=prod


spring:
  application:
    name: "Simple AWS Service"
  profiles:
    active: dev
